arch: amd64

dist: bionic

language: go

go:
  - 1.15.x

stages:
  - test
  - coverage and report

jobs:
  include:
    - stage: test
      script:
        - go test ./...
        - go test -v -coverprofile coverage.out ./...

    - stage: coverage and report
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - "saurab.mish@gmail.com"
    on_success: never
    on_failure: always
