arch: amd64

dist: bionic

language: go

go:
  - 1.15.x

stages:
  - test
  - cover
  - report

jobs:
  include:
    - stage: test
      script:
        - go test -v ./...

    - stage: cover
      script:
        - go test -v -coverprofile coverage.out ./...
        - go tool cover -html=coverage.out -o ./docs/coverage.html

    - stage: report
      script:
        - bash <(curl -s https://codecov.io/bash) -f ./docs/coverage.html

notifications:
  email:
    recipients:
      - "saurab.mish@gmail.com"
    on_success: never
    on_failure: always
